[build]
  base = "Frontend_Admin_Minsa"
  command = "npm run build"
  publish = "Frontend_Admin_Minsa/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200